name: uniconnect
description: "UniConnect - University life integration platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Styling
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # State Management
  provider: ^6.1.2

  # Navigation
  go_router: ^14.6.2

  # HTTP & API (simplified for demo)
  http: ^1.1.0
  json_annotation: ^4.9.0

  # Local Storage
  shared_preferences: ^2.3.2

  # Database
  sqflite: ^2.4.1
  path: ^1.9.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  logger: ^2.5.0

  # Push Notifications & Reminders
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4

  # Image & Asset Management
  cached_network_image: ^3.4.1

  # Animations
  lottie: ^3.2.0

  # Guided Tours
  tutorial_coach_mark: ^1.2.11

  # Maps
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Demo data assets
  assets:
    - assets/demo_data/
    - assets/Logos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
